site_name: Quimanima
site_url: https://quimanima.github.io/
site_description: Quimanima - Animations 2D with Python - Turtle for Chemistry.
site_author: Quimanima Team

repo_url: https://github.com/quimanima/quimanima